### ISSUE TITLE
Migrate helium-hardware-definitions

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-pyhelper#10] opened 2021-09-14 12:52 UTC
Move all imports that currently happen in Dockerfiles and/or manually copied into projects into hm-pyhelper. Import using PyPi instead.

Current location: https://github.com/NebraLtd/helium-hardware-definitions

**Comment by shawaj** [comment] 2021-09-16 19:05
Duplicate of #6

**Closed** 2021-09-17 07:59 UTC
